### ISSUE TITLE
Doesn't work with Meteor 1.3 beta 12

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/meteor-accounts-sandstorm#16]
Getting the following when attempting to refactor an app to Meteor 1.3 beta 12:

[[[[[ ~/Projects/List ]]]]]

=> Started proxy.
=> Started MongoDB.
[34mW20160304-09:13:59.337(-6)? (STDERR) [39m[35m[39m
[34mW20160304-09:13:59.347(-6)? (STDERR) [39m[35m/home/nolan/.meteor/packages/meteor-tool/.1.1.13-beta.12.767s8i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267[39m
[34mW20160304-09:13:59.348(-6)? (STDERR) [39m[35m						throw(ex);[39m
[34mW20160304-09:13:59.348(-6)? (STDERR) [39m[35m						      ^[39m
[34mW20160304-09:13:59.348(-6)? (STDERR) [39m[35mTypeError: Object [object Object] has no method 'onConnection'[39m
[34mW20160304-09:13:59.348(-6)? (STDERR) [39m[35m    at Package (packages/kenton_accounts-sandstorm/server.js:35:1)[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at packages/kenton_accounts-sandstorm/server.js:165:1[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at packages/kenton_accounts-sandstorm/server.js:165:1[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at /home/nolan/Projects/List/.meteor/local/build/programs/server/boot.js:245:10[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at Array.forEach (native)[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at Function._.each._.forEach (/home/nolan/.meteor/packages/meteor-tool/.1.1.13-beta.12.767s8i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20160304-09:13:59.349(-6)? (STDERR) [39m[35m    at /home/nolan/Projects/List/.meteor/local/build/programs/server/boot.js:140:5[39m
=> Exited with code: 8

**Comment by kentonv** [comment]
Fixed by d1bb02e and released as 0.2.1. Turns out this is not specific to Meteor 1.3, but rather depends on the order in which you declare your app's dependencies. Also note that I *think* this problem can only happen if you haven't declared a dependency on `accounts-base`. Note that `accounts-base` is no longer an implied dependency, but if you want `accounts-sandstorm` to behave in a backwards-compatible way to 0.1.x, you'll want to add `accounts-base` as an explicit dependency. Otherwise, `accounts-sandstorm` will no longer create users in the `Meteor.users` table.

**Comment by ndarilek** [comment]
So I'm not sure to what extent this will affect meteor-spk but it will likely help. Meteor 1.3 RC1 as released today introduces `meteor node`, which runs the version of Node associated with the given Meteor version, and `meteor npm` which does likewise for NPM. So it may be sufficient to check for releases > 1.3 and just run the relevant meteor subcommand rather than having to repack the tool for newer Meteor versions.

No rush on this, I'm porting a near-production Meteor app to 1.3 and figured I'd filter the churn for potentially useful things, and this seems like it'd make picking the right node/npm versions easier.
