### ISSUE TITLE
Support for applications not running out of site root

### ISSUE THREAD

**Issue by r0p0s3c** [sandstorm-io/meteor-accounts-sandstorm#17]
Currently it looks like the only applications running out of the site root (i.e. https://host/) are supported - both the client and server request/look for <host>/.sandstorm-login. It'd be better if URL_PATH_PREFIX or similar were to be used to support running out of a subdirectory

**Comment by kentonv** [comment]
Hmm. I'm curious: is there a Sandstorm app you are trying to port that involves running a Meteor app not at root? This seems like an unlikely scenario to me. I'm not against the change, just really curious to know what motivated it.

**Comment by r0p0s3c** [comment]
Hi @kentonv, I encountered this when trying to deploy Rocket.Chat (https://github.com/RocketChat/Rocket.Chat) in this way, i.e. in a subdirectory of the server root. I'm not actually using sandstorm, but thought this would be a useful fix to prevent unnecessary failed GETs

**Comment by kentonv** [comment]
Hmmmm. Actually, accounts-sandstorm really shouldn't be included in non-sandstorm builds at all.

I think we probably need to adjust the code so that accounts-sandstorm disables itself when not in Sandstorm, probably based on the `SANDSTORM` environment variable.

**Comment by kentonv** [comment]
(I will work on this soon.)

**Comment by r0p0s3c** [comment]
Understood, thanks for looking into it

**Comment by kentonv** [comment]
Sorry for the delay. Package version 0.2.2 fixes this by only enabling the package if the `SANDSTORM` environment variable is set.
