### ISSUE TITLE
Expose X-Sandstorm-Session-Id as well

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/meteor-accounts-sandstorm#25]
It seems it is needed to obtain `HackSessionContext` to be able to send e-mail from a grain of a Meteor app.

**Comment by kentonv** [comment]
I suppose now that we're associating data primarily with the connection rather than user accounts, this is straightforward. (It wouldn't make sense to store the session ID on a Meteor.users record, but it would make sense to put it on the connection object.)
