### ISSUE TITLE
Browser randomly adding "; charset=UTF-8" to XHR request content-type?

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/meteor-accounts-sandstorm#27]
In https://github.com/RocketChat/Rocket.Chat/issues/3055#issuecomment-215450873, @kiwano claimed to have seen the following error in the console:

> "couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8 at packages/kenton_accounts-sandstorm/server.js:138:1 at packages/kenton_accounts-sandstorm/server.js:49:1 at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) at packages/meteor/dynamics_nodejs.js:123:1 at packages/kenton_accounts-sandstorm/server.js:133:1 at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) at packages/meteor/dynamics_nodejs.js:...
> Stack trace:
> r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

It appears that somehow `; charset=UTF-8` was appended to the Content-Type of the XHR on the client side. This seems like incorrect browser behavior.

@kiwano reported this occurred with Iceweasel 38.7.1.

@kiwano, is this behavior consistent in Iceweasel? Does it happen in any other browsers?

**Comment by kiwano** [comment]
In terms of consistency, it's been happening for about a month or two now, through a few minor upgrades of Iceweasel (still happening on 38.8.0), and has happened in different instances of Iceweasel on different computers (including a fresh install on a new-to-me laptop). I haven't noticed this problem in Chrome, and haven't really tried any other browsers than those two at this point.

**Comment by kentonv** [comment]
Should be fixed by 2a9dc0a64c5bf14478f8c358b1d04f1ace8e8d4f, released as package version 0.4.1. Rocket.Chat will need to update.

**Comment by kentonv** [comment]
FWIW I haven't been able to repro using Firefox. I suspect this is something that was a bug once but has long-since been fixed, but Iceweasel is of course stuck in the past. :/

**Comment by kiwano** [comment]
Yeah, I've considered going to stock FF instead of continuing with Iceweasel, but I tend to cling tenaciously to the scraps of sanity offered by keeping as much of my software as possible coming from a single package management system (and single repo--or at least non-conflicting repos if I can manage that). I *think* my current admin policy breaks fewer things than package-manager-hell... ;P
