### ISSUE TITLE
conflict constraint

### ISSUE THREAD

**Issue by wiredots01** [sandstorm-io/meteor-accounts-sandstorm#35]
<img width="563" alt="screen shot 2017-09-14 at 10 39 26 am" src="https://user-images.githubusercontent.com/4254904/30409707-6815a788-9939-11e7-8099-7dad5be08f07.png">

pls check, I've encountered the error upon meteor run

**Comment by kentonv** [comment]
Hi Rommel,

This was fixed by accounts-sandstorm 0.7.0. Please update your package version.
