### ISSUE TITLE
Accounts.updateOrCreateUserFromExternalService() may be broken

### ISSUE THREAD

**Issue by Sing-Li** [sandstorm-io/meteor-accounts-sandstorm#6]
In the process of porting a meteor app to sandstorm.   I added the `kenton:accounts-sandstorm` package (and removing all the oauths providers, leaving only `accounts-password`) ... I keep getting a problem related to the  `login` variable not being defined in server.js of accounts-sandstorm:

The `console.log(login)` line outputs `undefined` in logs.

````
GET http://j1izdhrrrhhhwi4hahog.local.sandstorm.io:6080/.sandstorm-credentials 500 (Internal Server Error)r.call @ 2737201db08ba39f68ec1a2e6341935e1b8c764b.js:78r.get @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:78(anonymous function) @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:242t.Computation._compute @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:9t.Computation @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:9t.autorun @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:9(anonymous function) @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:242o @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:3o @ 

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:3

2737201db08ba39f68ec1a2e6341935e1b8c764b.js:242 Error: failed [500] TypeError: Cannot read property 'userId' of undefined    

 at packages/kenton:accounts-sandstorm/server.js:52:1    

 at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)

    at a (2737201db08ba39f68ec1a2e6341935e1b8c764b.js:78)

    at XMLHttpRequest.r.call.g.onreadystatechange 

(2737201db08ba39f68ec1a2e6341935e1b8c764b.js:78)
````

**Comment by kentonv** [comment]
Hmm, I'm not able to reproduce this with Meteor 1.1.0.3 using the "parties" example app (which does login). What version are you using?

Note that you really should remove accounts-password as well on Sandstorm, though I don't see how that could cause the problem.

**Comment by Sing-Li** [comment]
My bad. Should have closed this.  I was not handling the service callback correctly. Thanks for looking into it.
